spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

endpoints:
  health:
    sensitive: false

---

spring:
  profiles: default
  jpa:
    database: HSQL

---

spring:
  profiles: pcf
  jpa:
    database: MYSQL

---

spring:
  profiles: pws
  jpa:
    database: POSTGRESQL

---

spring:
  profiles: lattice
  jpa:
    database: MYSQL